// Golden payload-transform vectors.
//
// GENERATED by tools/extract_golden.py from the upstream C# fixture --
// do not edit by hand.
//
// 55 vectors across 5 builds. Bit counts are chosen to
// exercise every staging boundary of the transform: 0, 1, 7 (tail only),
// 8 (one byte), 31/32 (32-bit word edge), 63/64/65 (64-bit word edge) and
// 287/288 (multi-word with and without a partial tail).

/// The shared plaintext payload every vector transforms.
pub const PAYLOAD_HEX: &str = "BFDF6F9EA1F27BA00000C66EAFAF2E0000339C0DD34B0C45C48063038003562A43C0C949";

/// Actor net GUID used to derive the seed in the reference fixture.
pub const ACTOR_NET_GUID: u32 = 2;

/// `(branch, bit_count, expected_output_hex)`
pub const VECTORS: [(&str, usize, &str); 55] = [
    ("++Ares-Core+release-12.10", 0, ""),
    ("++Ares-Core+release-12.10", 1, "01"),
    ("++Ares-Core+release-12.10", 7, "5F"),
    ("++Ares-Core+release-12.10", 8, "50"),
    ("++Ares-Core+release-12.10", 31, "49629D71"),
    ("++Ares-Core+release-12.10", 32, "A8FC7EF3"),
    ("++Ares-Core+release-12.10", 63, "47D3ED3F73178739"),
    ("++Ares-Core+release-12.10", 64, "10AC2E70AD1212C0"),
    ("++Ares-Core+release-12.10", 65, "7721410F808044D200"),
    ("++Ares-Core+release-12.10", 287, "100CA461300F080493400100000040394E5120000000B0792C626000000080FE7F3C2000"),
    ("++Ares-Core+release-12.10", 288, "398140967937107E4FA28FEB1FD75CAED71D618B1940D9C6092174B47BA199FD5E2F8393"),
    ("++Ares-Core+release-12.11", 0, ""),
    ("++Ares-Core+release-12.11", 1, "01"),
    ("++Ares-Core+release-12.11", 7, "19"),
    ("++Ares-Core+release-12.11", 8, "F4"),
    ("++Ares-Core+release-12.11", 31, "3C77997B"),
    ("++Ares-Core+release-12.11", 32, "18F42FF1"),
    ("++Ares-Core+release-12.11", 63, "8EF2B27ADAE67472"),
    ("++Ares-Core+release-12.11", 64, "D1545FF0BD2FB867"),
    ("++Ares-Core+release-12.11", 65, "E7A9BFB07CFF24CF01"),
    ("++Ares-Core+release-12.11", 287, "43FE3C8BA5D21FEFBFA741CE0E0071A3F279A1C6E817075ACF20662447D9E50F75F1481D"),
    ("++Ares-Core+release-12.11", 288, "022F9877FE647DE0F27D5FE813C5FC03BA3EA8C3D7C7BB79B8E1C7755F405825611C0C99"),
    ("++Ares-Core+release-13.00", 0, ""),
    ("++Ares-Core+release-13.00", 1, "01"),
    ("++Ares-Core+release-13.00", 7, "55"),
    ("++Ares-Core+release-13.00", 8, "88"),
    ("++Ares-Core+release-13.00", 31, "01B0DD66"),
    ("++Ares-Core+release-13.00", 32, "901B662B"),
    ("++Ares-Core+release-13.00", 63, "029693CD8ADFD510"),
    ("++Ares-Core+release-13.00", 64, "224FB261A44ADF65"),
    ("++Ares-Core+release-13.00", 65, "C8336218A9D2979001"),
    ("++Ares-Core+release-13.00", 287, "4FE8F025C0F05BA5DBDD798E8A23E32372F1B49C61C270104E7BD61458C2A433218A1A77"),
    ("++Ares-Core+release-13.00", 288, "8772F8F262B8A7D2A6703E5E961BA7D703AC43D56EE0CC82F4BE1987FC7847365E6B7C32"),
    ("++Ares-Core+release-13.01", 0, ""),
    ("++Ares-Core+release-13.01", 1, "00"),
    ("++Ares-Core+release-13.01", 7, "66"),
    ("++Ares-Core+release-13.01", 8, "33"),
    ("++Ares-Core+release-13.01", 31, "C2B2EA65"),
    ("++Ares-Core+release-13.01", 32, "ABDBCFFA"),
    ("++Ares-Core+release-13.01", 63, "196EDFE8D117154D"),
    ("++Ares-Core+release-13.01", 64, "96407A158400136C"),
    ("++Ares-Core+release-13.01", 65, "9B158480536C754001"),
    ("++Ares-Core+release-13.01", 287, "03417AC58400D36B853918CF2FD40E14D17390D76FBE6E2343D7236F626CA9FF9163B932"),
    ("++Ares-Core+release-13.01", 288, "7A3611024CB0D5010F95CEE80D1454FC9BFA0206B31864A0621CF3DAE6B7524FDEFA05A3"),
    ("++Ares-Core+release-13.02", 0, ""),
    ("++Ares-Core+release-13.02", 1, "00"),
    ("++Ares-Core+release-13.02", 7, "46"),
    ("++Ares-Core+release-13.02", 8, "B3"),
    ("++Ares-Core+release-13.02", 31, "919A9E63"),
    ("++Ares-Core+release-13.02", 32, "9F2ADA1D"),
    ("++Ares-Core+release-13.02", 63, "DA9DA62A9993DA4E"),
    ("++Ares-Core+release-13.02", 64, "5A50DFF6BED22CC7"),
    ("++Ares-Core+release-13.02", 65, "5F6596632DA86F7B01"),
    ("++Ares-Core+release-13.02", 287, "B10ED4B77D1031CB749931F80C11719110B1AC15F65AAB929706868895077F43AF407273"),
    ("++Ares-Core+release-13.02", 288, "0F926639D681FAB6D03122E222E923CCC987DA22625B2BFC077F432F912DBD96F2368E1E"),
];
