//! Type-aware field decoders for Unreal Engine replay primitives.
//!
//! # Purpose
//!
//! The replay pipeline records every field update as raw bits. This crate
//! converts those bits into typed values by applying the same decoding logic
//! that the game client uses (ported from the C# reference parser).
//!
//! # Design: additive overlay
//!
//! Decoding is *additive*: raw bits are always preserved. A successful decode
//! populates one of the `value_*` slots; a failure leaves them all `None` and
//! increments an error counter. This guarantees forward compatibility: unknown
//! fields or layout changes never lose data, they just lack typed overlays
//! until the decoder is updated. Nothing here ever substitutes a plausible
//! value for one it could not read.
//!
//! # Supported types
//!
//! | Type | Bits consumed | Value slot |
//! |------|---------------|------------|
//! | Bool | 1 | `value_bool` |
//! | Byte | 8 | `value_i64` |
//! | EnumByte | 8 | `value_i64` |
//! | Int32 | 32 | `value_i64` |
//! | UInt32 | 32 | `value_i64` |
//! | UInt64 | 64 | `value_i64` |
//! | Float | 32 | `value_f64` |
//! | Double | 64 | `value_f64` |
//! | FString | variable | `value_str` |
//! | FName | variable | `value_str` |
//! | ObjectNetGuid | variable (IntPacked) | `value_i64` |
//! | Guid | 128 | `value_str` (hex) |
//! | SerializedInt(max) | variable | `value_i64` |
//! | EnumRemainingBits | all remaining | `value_i64` |
//! | GameplayTag | variable (IntPacked) | `value_i64` (tag index) |
//! | ByteArray(max) | variable | `value_str` (hex) |
//! | FVector(double) | 192 | `value_str` (compact) |
//! | FVector(float) | 96 | `value_str` (compact) |
//! | VectorNetQuantize(1/10/100) | variable | `value_str` (compact) |
//! | VectorNetQuantizeNormal | ~48 (3 x 16 serialized) | `value_str` (compact) |
//! | RotationShort | 3 x (1+16) max | `value_str` (compact) |
//! | RotationByte | 3 x (1+8) max | `value_str` (compact) |
//! | Transform | 4 x 32 + 3 x 32 + 3 x 32 = 320 | `value_str` (compact) |
//! | RepMovement | variable | `value_str` (JSON object, 8 members) |
//! | RepLayoutDynamicArray | variable | *Raw* (not decoded) |
//!
//! Two decoders sit outside that table because they key off the field's name
//! rather than a declared type: [`structs`] for the named struct blobs, and
//! [`effect`] for the `EffectContainer` arrays, which fill `value_str` with a
//! JSON array. Both are additive in the same sense -- raw bits survive.
//!
//! # Module map
//!
//! | Module | What it owns |
//! |--------|--------------|
//! | `types` | The model structs and their `Display` forms |
//! | `decode` | `FieldType`, `DecodedValue` and the dispatch; `scalar` and `geometry` hold the readers |
//! | `overlay` | The `(group_path, field_name)` table, its hash index and the resolution order |
//! | `table` | GENERATED by `tools/extract_descriptors.py` -- never hand-edited |
//! | `array` | The RepLayout dynamic-array walker and the nesting schema |
//! | `structs` | The three named struct blobs, one module each |
//! | `effect` | The `EffectContainer` arrays: framing, elements, JSON |
//!
//! # Feature flags
//!
//! `decode_field` and the model types in [`types`] are the crate's core and are
//! always compiled: everything else is expressed in terms of them, so there is
//! no flag for them. The four decoders layered on top are independent of each
//! other and each can be left out:
//!
//! | Feature | Brings in | Notes |
//! |---------|-----------|-------|
//! | `overlay` | [`OverlayTable`], [`apply_overlay_with_handle`], `OVERLAY_TABLE` | Also compiles the 1,185-entry generated table |
//! | `array` | [`decode_struct_array`] and [`COMBAT_ROUNDS_SCHEMA`] | |
//! | `structs` | [`structs`] | |
//! | `effect` | [`effect`] | |
//!
//! All four are on by default, so a consumer that does nothing gets the whole
//! crate. `overlay` is the one worth dropping if the primitive decoders are all
//! you want: it is what pulls in the 1,185-entry generated table.

#![forbid(unsafe_code)]

mod decode;
mod types;

#[cfg(feature = "array")]
mod array;
/// Effect-blob decoder for the `EffectContainer` arrays that RPCs carry as
/// `FloatValues` / `ObjectValues` / `VectorValues`. Wired into the export path
/// through [`effect::decode_effect_blob_json`]; one RPC is deliberately left to
/// the Python port in `tools/to_valplay_bundle.py`. See the module docs.
#[cfg(feature = "effect")]
pub mod effect;
#[cfg(feature = "overlay")]
mod overlay;
#[cfg(feature = "structs")]
pub mod structs;
#[cfg(feature = "overlay")]
mod table;
#[cfg(test)]
mod tests;

pub use decode::{DecodeError, DecodedValue, FieldType, decode_field};
pub use types::{FQuat, FRepMovement, FRotator, FTransform, FVector, RotatorQuantization};

#[cfg(feature = "array")]
pub use array::{
    ArrayDecodeStats, ArrayFieldSchema, COMBAT_ROUNDS_SCHEMA, FlattenedField, MAX_ELEMENTS,
    MAX_FIELDS_PER_ELEMENT, MAX_RECURSION_DEPTH, decode_struct_array,
};
#[cfg(feature = "effect")]
pub use effect::{EffectArrayKind, EffectBlobError, decode_effect_blob_json};
#[cfg(feature = "overlay")]
pub use overlay::{
    DecodeErrorKind, OverlayEntry, OverlayErrorReport, OverlayErrorRow, OverlayHandleEntry,
    OverlayStats, OverlayTable, apply_overlay, apply_overlay_with_handle, resolve_field_type,
};
#[cfg(feature = "overlay")]
pub use table::{OVERLAY_HANDLE_TABLE, OVERLAY_TABLE};
