//! Overlay table: maps `(group_path, field_name)` -> [`FieldType`] and applies
//! decoding to produce typed values.
//!
//! The entries themselves are generated by `tools/extract_descriptors.py` into
//! `table.rs` as a sorted static slice. This module owns two things on top of
//! that: the hash index in [`index`], which answers the ~2M table probes a
//! replay makes without walking the sorted slice, and
//! [`apply_overlay_with_handle`], the resolution order that decides which entry
//! a wire field belongs to.
//!
//! Sortedness of the generated slice is no longer what makes lookup work, but
//! `tests::overlay::table_is_sorted` still asserts it: it is the generator's
//! contract, and the reference binary search that the identity tests compare
//! the index against depends on it.

mod index;
mod stats;

use std::sync::OnceLock;

use crate::decode::{DecodeError, DecodedValue, FieldType, decode_field};
use index::{OverlayIndex, handle_hash, handle_hash_from_group, name_hash, name_hash_from_group};

pub use index::{GroupHashState, group_hash_state};
pub use stats::{DecodeErrorKind, OverlayErrorReport, OverlayErrorRow, OverlayStats};

/// A single entry in the overlay table.
///
/// The table is sorted by `(group_path, field_name)`.
#[derive(Debug, Clone, Copy)]
pub struct OverlayEntry {
    pub group_path: &'static str,
    pub field_name: &'static str,
    pub field_type: FieldType,
}

/// Maps a C# descriptor's explicit property handle back to its field name.
///
/// Keeping the type in [`OverlayEntry`] makes generated type corrections apply
/// equally to direct-name and handle-fallback lookups.
#[derive(Debug, Clone, Copy)]
pub struct OverlayHandleEntry {
    pub group_path: &'static str,
    pub handle: u32,
    pub field_name: &'static str,
}

/// The overlay table -- a static slice of entries plus a lazily built index.
///
/// Lookup is O(1) through the hash index. The index is built on the first
/// lookup and reused from then on, which is what lets construction stay a
/// `const fn` usable in a `static` while a table that is never queried still
/// costs nothing.
#[derive(Debug, Clone)]
pub struct OverlayTable {
    entries: &'static [OverlayEntry],
    handle_entries: &'static [OverlayHandleEntry],
    index: OnceLock<OverlayIndex>,
}

impl OverlayTable {
    /// Create a table from a static slice.
    #[must_use]
    pub const fn new(entries: &'static [OverlayEntry]) -> Self {
        Self {
            entries,
            handle_entries: &[],
            index: OnceLock::new(),
        }
    }

    /// Create a table with explicit-handle fallback metadata.
    #[must_use]
    pub const fn with_handles(
        entries: &'static [OverlayEntry],
        handle_entries: &'static [OverlayHandleEntry],
    ) -> Self {
        Self {
            entries,
            handle_entries,
            index: OnceLock::new(),
        }
    }

    #[inline]
    fn index(&self) -> &OverlayIndex {
        self.index
            .get_or_init(|| OverlayIndex::build(self.entries, self.handle_entries))
    }

    /// Look up the field type for a `(group_path, field_name)` pair.
    #[must_use]
    pub fn lookup(&self, group_path: &str, field_name: &str) -> Option<FieldType> {
        self.lookup_hashed(name_hash(group_path, field_name), group_path, field_name)
    }

    /// [`Self::lookup`] with the key hash already computed.
    ///
    /// The overlay's boolean fallback probes two tables with the same key, so
    /// hashing once and passing the result down is what keeps that fallback
    /// from costing a second pass over the group path.
    #[inline]
    fn lookup_hashed(&self, hash: u64, group_path: &str, field_name: &str) -> Option<FieldType> {
        let entries = self.entries;
        let position = self
            .index()
            .find_name(entries, hash, group_path, field_name)?;
        Some(entries[position].field_type)
    }

    /// Look up the `b`-prefixed spelling of `field_name`.
    ///
    /// See [`resolve_entry`] for why this fallback exists and the `index`
    /// module docs for why no prefixed key is ever built. The export path
    /// always arrives with the key hash already in hand, so this string-taking
    /// form exists only for the identity tests.
    #[cfg(test)]
    pub(crate) fn lookup_b_prefixed(
        &self,
        group_path: &str,
        field_name: &str,
    ) -> Option<FieldType> {
        self.lookup_b_prefixed_hashed(name_hash(group_path, field_name), group_path, field_name)
    }

    /// [`Self::lookup_b_prefixed`] with the key hash already computed.
    #[inline]
    fn lookup_b_prefixed_hashed(
        &self,
        hash: u64,
        group_path: &str,
        field_name: &str,
    ) -> Option<FieldType> {
        let entries = self.entries;
        let position = self
            .index()
            .find_b_prefixed_name(entries, hash, group_path, field_name)?;
        Some(entries[position].field_type)
    }

    /// Look up the descriptor field name for an explicit property handle.
    #[must_use]
    pub fn lookup_handle(&self, group_path: &str, handle: u32) -> Option<&'static str> {
        self.lookup_handle_hashed(handle_hash(group_path, handle), group_path, handle)
    }

    /// [`Self::lookup_handle`] with the key hash already computed.
    ///
    /// The export path always has the group hash state in hand, so this form
    /// avoids re-hashing the (long) group path on the handle fallback too.
    #[inline]
    fn lookup_handle_hashed(
        &self,
        hash: u64,
        group_path: &str,
        handle: u32,
    ) -> Option<&'static str> {
        let handle_entries = self.handle_entries;
        let position = self
            .index()
            .find_handle(handle_entries, hash, group_path, handle)?;
        Some(handle_entries[position].field_name)
    }

    /// Number of entries.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the table is empty.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// The binary search this table used before the hash index, kept as the
    /// reference the identity tests compare against. Sortedness of the
    /// generated slice is what makes it correct, and `table_is_sorted` asserts
    /// that.
    #[cfg(test)]
    pub(crate) fn lookup_by_binary_search(
        &self,
        group_path: &str,
        field_name: &str,
    ) -> Option<FieldType> {
        let idx = self
            .entries
            .binary_search_by(|entry| {
                entry
                    .group_path
                    .cmp(group_path)
                    .then_with(|| entry.field_name.cmp(field_name))
            })
            .ok()?;
        Some(self.entries[idx].field_type)
    }

    /// Handle-table counterpart of [`Self::lookup_by_binary_search`].
    #[cfg(test)]
    pub(crate) fn lookup_handle_by_binary_search(
        &self,
        group_path: &str,
        handle: u32,
    ) -> Option<&'static str> {
        let idx = self
            .handle_entries
            .binary_search_by(|entry| {
                entry
                    .group_path
                    .cmp(group_path)
                    .then_with(|| entry.handle.cmp(&handle))
            })
            .ok()?;
        Some(self.handle_entries[idx].field_name)
    }

    /// The `b`-prefix fallback expressed the way it was before the index:
    /// a plain lookup of the concatenated key. Test-only reference.
    #[cfg(test)]
    pub(crate) fn lookup_b_prefixed_by_binary_search(
        &self,
        group_path: &str,
        field_name: &str,
    ) -> Option<FieldType> {
        self.lookup_by_binary_search(group_path, &format!("b{field_name}"))
    }
}

/// Result of applying the overlay to a single field.
pub struct OverlayResult {
    pub value_i64: Option<i64>,
    pub value_f64: Option<f64>,
    pub value_bool: Option<bool>,
    pub value_str: Option<String>,
}

impl OverlayResult {
    /// The all-null result: a decode was attempted and did not produce a value.
    /// The caller keeps `raw_bits`; nothing is ever fabricated in its place.
    const NONE: Self = Self {
        value_i64: None,
        value_f64: None,
        value_bool: None,
        value_str: None,
    };

    fn from_decoded(value: DecodedValue) -> Self {
        match value {
            DecodedValue::I64(v) => Self {
                value_i64: Some(v),
                ..Self::NONE
            },
            DecodedValue::F64(v) => Self {
                value_f64: Some(v),
                ..Self::NONE
            },
            DecodedValue::Bool(v) => Self {
                value_bool: Some(v),
                ..Self::NONE
            },
            DecodedValue::Str(v) => Self {
                value_str: Some(v),
                ..Self::NONE
            },
        }
    }
}

/// Apply the type overlay to a single field.
///
/// `group_state` is the cacheable half of the key hash -- see [`group_hash_state`].
/// A caller probing many fields against the same group path computes it once and
/// reuses it; a one-off caller passes [`group_hash_state`]`(group_path)`.
///
/// Returns `None` if the field has no type mapping or is Raw/Skip.
/// Returns `Some(OverlayResult)` on success (values filled) or on decode
/// failure (all None -- the raw_bits remain).
pub fn apply_overlay(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&str>,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    apply_overlay_inner(
        table,
        group_path,
        group_state,
        field_name,
        None,
        None,
        raw_bits,
        bit_count,
        stats,
    )
}

/// Apply the overlay with the replay field's handle available as a fallback.
///
/// `group_state` is the cacheable half of the key hash -- see [`group_hash_state`].
/// Direct name lookup, including the narrow Unreal `b`-prefix fallback, stays
/// authoritative. The explicit handle is consulted only when both miss.
#[allow(clippy::too_many_arguments)]
pub fn apply_overlay_with_handle(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&str>,
    handle: u32,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    apply_overlay_inner(
        table,
        group_path,
        group_state,
        field_name,
        Some(handle),
        None,
        raw_bits,
        bit_count,
        stats,
    )
}

/// [`apply_overlay_with_handle`] with the field's `compatible_checksum`.
///
/// Both export paths pass one, and neither pays for it: each already walks the
/// schema for the field's name, and the same `NetFieldExport` carries the
/// checksum. The property path was first wired without it on the assumption
/// that reaching the checksum there meant a second lookup on the hottest loop
/// in the export; extending the existing walk to return both costs nothing, and
/// `tools/bench_export.py` measured no slowdown.
#[allow(clippy::too_many_arguments)]
pub fn apply_overlay_with_checksum(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&str>,
    handle: u32,
    checksum: Option<u32>,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    apply_overlay_inner(
        table,
        group_path,
        group_state,
        field_name,
        Some(handle),
        checksum,
        raw_bits,
        bit_count,
        stats,
    )
}

/// The full resolution order a replicated field gets, for callers that hold a
/// name and a handle but not a whole row.
///
/// Exists because the array walker was doing only the first of the three steps
/// -- a bare name lookup -- so a flattened leaf could miss a type that the same
/// field would have been given outside an array. Duplicating the order at the
/// call site is how the two drift apart, so it is published once here.
#[must_use]
pub fn resolve_field_type(
    table: &OverlayTable,
    group_path: &str,
    field_name: Option<&str>,
    handle: Option<u32>,
) -> Option<FieldType> {
    resolve_field_type_with_checksum(table, group_path, field_name, handle, None)
}

/// [`resolve_field_type`] with the field's `compatible_checksum` in hand.
///
/// The checksum is the last resort in the order, so passing it can only resolve
/// fields that would otherwise have stayed raw.
#[must_use]
pub fn resolve_field_type_with_checksum(
    table: &OverlayTable,
    group_path: &str,
    field_name: Option<&str>,
    handle: Option<u32>,
    checksum: Option<u32>,
) -> Option<FieldType> {
    resolve_entry(
        table,
        group_path,
        group_hash_state(group_path),
        field_name,
        handle,
        checksum,
    )
    .map(|(field_type, _)| field_type)
}

/// Game-mode sibling classes that carry the SAME property set under a
/// different class name, mapped to the class the table is keyed on.
///
/// Swiftplay replays -- 5 of the 215-replay corpus -- declare
/// `Swiftplay_EoRCredits_GameState_C` and `Swiftplay_EoRCredits_PlayerState_C`
/// where a Bomb replay declares `BombGameState_C` and `BombPlayerState_C`. The
/// FIELD names are identical: `RoundResults`, `BombState`, `MatchState`,
/// `TeamEconomy`, `PossessedCharacter`, `PlayerInfo`, `CompetitiveTier`,
/// `NumUltimatePoints`, `Subject`. Only the class differs, so every one of
/// those fields was arriving untyped.
///
/// An ALIAS rather than 28 duplicated table entries, for three reasons: the
/// duplicates would encode one fact 28 times, they would drift the moment
/// `extract_descriptors.py` regenerates, and `ADDITIONS` in
/// `apply_type_corrections.py` is explicitly the "no descriptor declares this"
/// mechanism -- these descriptors are not silent, they name a sibling class.
///
/// Soundness rests on same-name properties having the same WIDTH on both
/// classes, which is exactly what `check_decode_errors_corpus.py` tests: a
/// mistyped width surfaces as `BitIo` or `NotFullyConsumed` on one of the five
/// Swiftplay replays.
///
/// Only the two base classes are aliased. The `_ClassNetCache` and
/// `<Class>:<Function>` forms are NOT, because the table holds zero entries
/// for the Bomb spellings of those, so aliasing them would be an untested
/// claim buying nothing.
const GROUP_ALIASES: &[(&str, &str)] = &[
    (
        "/Game/GameModes/_Development/Swiftplay_EndOfRoundCredits\
/Swiftplay_EoRCredits_GameState.Swiftplay_EoRCredits_GameState_C",
        "/Game/GameModes/Bomb/BombGameState.BombGameState_C",
    ),
    (
        "/Game/GameModes/_Development/Swiftplay_EndOfRoundCredits\
/Swiftplay_EoRCredits_PlayerState.Swiftplay_EoRCredits_PlayerState_C",
        "/Game/GameModes/Bomb/BombPlayerState.BombPlayerState_C",
    ),
];

/// The class whose table entries `group_path` should fall back to, if any.
#[must_use]
fn alias_group(group_path: &str) -> Option<&'static str> {
    GROUP_ALIASES
        .iter()
        .find(|(from, _)| *from == group_path)
        .map(|(_, to)| *to)
}

/// `group_path` rewritten to the class the table and the struct-blob decoders
/// are keyed on, or unchanged when it already is one.
///
/// Published because the overlay is not the only thing that keys on a class
/// name: `vrfkit`'s struct-blob dispatch gates `RoundResults` and `TeamEconomy`
/// on the group containing `BombGameState`, and a Swiftplay replay carries
/// both under its own game state. Two places deciding "is this a game state"
/// from two different string tests is how they drift; this is the one table.
#[must_use]
pub fn canonical_group(group_path: &str) -> &str {
    alias_group(group_path).unwrap_or(group_path)
}

/// `AActor` / `USceneComponent` object references that Unreal replicates on
/// every actor, always as a NetGUID.
///
/// The C# descriptors declare these only for the classes they happen to cover.
/// On 02d4d478 that leaves them typed on 129 group/field pairs (4,601 rows) and
/// untyped on 203 more (6,048 rows) -- the same four names, the same encoding,
/// simply no table entry, because the group is a Blueprint the reference never
/// described. The type is fixed by the engine and does not vary by class, so
/// resolving it by name is a statement about Unreal rather than a guess about
/// any one Blueprint.
///
/// A fallback and not table rows: the 203 pairs are what ONE replay happened to
/// spawn, so a table would be a snapshot of this match's agent lineup, stale for
/// the next one. It runs last, so a class that really does declare one of these
/// names as something else keeps its declared type.
const ENGINE_OBJECT_REFS: [&str; 4] = ["Owner", "Instigator", "AttachParent", "Controller"];

/// The type a `compatible_checksum` was learned to carry, or `None`.
///
/// Unreal hashes a property's type into its checksum alongside its name, so a
/// checksum identifies a property in a way a name cannot -- across the RPC
/// groups here exactly one pair of distinct names collides, while 38 of 211
/// parameter names carry more than one checksum. `CHECKSUM_TYPES` is generated
/// from the fields this table already declares, and omits any checksum whose
/// donors disagreed, so a lookup that returns `Some` is a type at least one
/// descriptor stated for the same property.
#[must_use]
pub fn lookup_checksum(checksum: u32) -> Option<FieldType> {
    let index = crate::checksum_table::CHECKSUM_TYPES
        .binary_search_by_key(&checksum, |(key, _)| *key)
        .ok()?;
    Some(crate::checksum_table::CHECKSUM_TYPES[index].1)
}

/// The full order, then the same order again against the aliased class, then
/// the engine-level object references by name.
///
/// Retrying the WHOLE order rather than just the name lookup keeps the alias
/// from being a fourth resolution step with its own rules -- an aliased field
/// gets the b-prefix and handle fallbacks exactly as a native one does.
fn resolve_entry<'a>(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&'a str>,
    handle: Option<u32>,
    checksum: Option<u32>,
) -> Option<(FieldType, &'a str)> {
    if let Some(hit) = resolve_in_group(table, group_path, group_state, field_name, handle) {
        return Some(hit);
    }
    // Not a `let` chain: those are stable only from 1.88 and the MSRV is 1.86.
    let aliased_hit = alias_group(group_path).and_then(|aliased| {
        resolve_in_group(
            table,
            aliased,
            group_hash_state(aliased),
            field_name,
            handle,
        )
    });
    if let Some(hit) = aliased_hit {
        return Some(hit);
    }
    let name = field_name?;
    if ENGINE_OBJECT_REFS.contains(&name) {
        return Some((FieldType::ObjectNetGuid, name));
    }
    // Last, and last on purpose: a checksum match is a type some descriptor
    // stated for the same property on another class, which is weaker than
    // anything declared for this one.
    lookup_checksum(checksum?).map(|field_type| (field_type, name))
}

/// Resolve which table entry a wire field belongs to within ONE group, and the
/// name to report it under if the decode later fails.
///
/// Order: the declared name, then the `b`-prefixed spelling of it, then the
/// explicit property handle.
///
/// # Why the `b`-prefix step exists
///
/// The C# descriptors bind a property to its handle number and carry a name
/// only as a label, so a descriptor that spells a boolean
/// `bDeathMontageEffectOverrideIsQueued` still matches a wire field the replay
/// declares as `DeathMontageEffectOverrideIsQueued`. Our table is keyed on the
/// name, so that spelling difference makes the lookup miss and the field stays
/// raw where the reference has a plain bool.
///
/// Narrow by construction: it only fires when the direct lookup already missed,
/// and it can only hit an entry that the C# author spelled with the Unreal
/// boolean prefix. Re-measured against the current 1,233-entry table by joining
/// every distinct `(group, name)` 02d4d478 exports against it, RPC parameters
/// under the group `sink/rpc.rs` actually asks with: 632 rows resolve this way
/// and no others. They are ONE property name, arriving on two RPC groups --
/// `MulticastNotifyDamage_Point` (581 rows) and `_Base` (51). The figure stood
/// at "581 rows, exactly one field", measured when the table held 1,054
/// entries; it counted the larger group and not its sibling.
fn resolve_in_group<'a>(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&'a str>,
    handle: Option<u32>,
) -> Option<(FieldType, &'a str)> {
    if let Some(name) = field_name {
        // One hash serves both probes; see the `index` module docs. The group
        // path half is already in `group_state`, so only the field name is
        // folded here -- that is the whole point of caching it.
        let hash = name_hash_from_group(group_state, name);
        if let Some(field_type) = table
            .lookup_hashed(hash, group_path, name)
            .or_else(|| table.lookup_b_prefixed_hashed(hash, group_path, name))
        {
            return Some((field_type, name));
        }
    }

    let handle = handle?;
    let descriptor_name = table.lookup_handle_hashed(
        handle_hash_from_group(group_state, handle),
        group_path,
        handle,
    )?;
    let field_type = table.lookup_hashed(
        name_hash_from_group(group_state, descriptor_name),
        group_path,
        descriptor_name,
    )?;
    Some((field_type, field_name.unwrap_or(descriptor_name)))
}

#[allow(clippy::too_many_arguments)]
fn apply_overlay_inner(
    table: &OverlayTable,
    group_path: &str,
    group_state: GroupHashState,
    field_name: Option<&str>,
    handle: Option<u32>,
    checksum: Option<u32>,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    let (field_type, diagnostic_name) =
        match resolve_entry(table, group_path, group_state, field_name, handle, checksum) {
            Some(resolved) => resolved,
            None => {
                if field_name.is_none() {
                    stats.no_field_name += 1;
                } else {
                    stats.not_in_table += 1;
                }
                return None;
            }
        };

    if matches!(field_type, FieldType::Raw | FieldType::Skip) {
        stats.raw_or_skip += 1;
        return None;
    }

    let data = match raw_bits {
        Some(d) if bit_count > 0 => d,
        _ => {
            // Zero-bit field with a typed decoder -- unusual but not an error.
            if bit_count == 0 && field_type == FieldType::EnumRemainingBits {
                stats.decoded_ok += 1;
                return Some(OverlayResult {
                    value_i64: Some(0),
                    ..OverlayResult::NONE
                });
            }
            stats.decoded_err += 1;
            stats.error_report.record(
                group_path,
                diagnostic_name,
                field_type,
                bit_count,
                DecodeErrorKind::ZeroBits,
            );
            return Some(OverlayResult::NONE);
        }
    };

    match decode_field(field_type, data, bit_count) {
        Ok(value) => {
            stats.decoded_ok += 1;
            Some(OverlayResult::from_decoded(value))
        }
        Err(e) => {
            stats.decoded_err += 1;
            let kind = match &e {
                DecodeError::BitIo(_) => DecodeErrorKind::Eof,
                DecodeError::NotFullyConsumed { .. } => DecodeErrorKind::Residual,
                DecodeError::RawOrSkip => DecodeErrorKind::ZeroBits, // unreachable here
                // A UInt64 that overflows i64 is a value-range rejection, not a
                // bit-level failure; no dedicated kind exists, so it is bucketed
                // with Residual. Defensive: does not fire on supported replays.
                DecodeError::UnsignedOverflow { .. } => DecodeErrorKind::Residual,
            };
            stats
                .error_report
                .record(group_path, diagnostic_name, field_type, bit_count, kind);
            Some(OverlayResult::NONE)
        }
    }
}
