//! Overlay table: maps `(group_path, field_name)` -> [`FieldType`] and applies
//! decoding to produce typed values.
//!
//! The table is generated by `tools/extract_descriptors.py` and compiled into
//! the binary as a static `phf` map (or, for now, a sorted slice with binary
//! search -- no extra dependency needed and the lookup is fast enough for 650
//! entries at millions of rows).

use std::collections::HashMap;

use crate::decode::{DecodeError, DecodedValue, FieldType, decode_field};

/// A single entry in the overlay table.
///
/// The table is sorted by `(group_path, field_name)` for binary search.
#[derive(Debug, Clone, Copy)]
pub struct OverlayEntry {
    pub group_path: &'static str,
    pub field_name: &'static str,
    pub field_type: FieldType,
}

/// Maps a C# descriptor's explicit property handle back to its field name.
///
/// Keeping the type in [`OverlayEntry`] makes generated type corrections apply
/// equally to direct-name and handle-fallback lookups.
#[derive(Debug, Clone, Copy)]
pub struct OverlayHandleEntry {
    pub group_path: &'static str,
    pub handle: u32,
    pub field_name: &'static str,
}

/// The overlay table -- a sorted slice of entries.
///
/// Lookup is O(log n) via binary search on the composite key.
#[derive(Debug, Clone)]
pub struct OverlayTable {
    entries: &'static [OverlayEntry],
    handle_entries: &'static [OverlayHandleEntry],
}

impl OverlayTable {
    /// Create a table from a pre-sorted static slice.
    ///
    /// # Panics (debug only)
    ///
    /// Debug-asserts that the slice is sorted.
    #[must_use]
    pub const fn new(entries: &'static [OverlayEntry]) -> Self {
        Self {
            entries,
            handle_entries: &[],
        }
    }

    /// Create a table with explicit-handle fallback metadata.
    #[must_use]
    pub const fn with_handles(
        entries: &'static [OverlayEntry],
        handle_entries: &'static [OverlayHandleEntry],
    ) -> Self {
        Self {
            entries,
            handle_entries,
        }
    }

    /// Look up the field type for a `(group_path, field_name)` pair.
    #[must_use]
    pub fn lookup(&self, group_path: &str, field_name: &str) -> Option<FieldType> {
        let idx = self
            .entries
            .binary_search_by(|entry| {
                entry
                    .group_path
                    .cmp(group_path)
                    .then_with(|| entry.field_name.cmp(field_name))
            })
            .ok()?;
        Some(self.entries[idx].field_type)
    }

    /// Look up the descriptor field name for an explicit property handle.
    #[must_use]
    pub fn lookup_handle(&self, group_path: &str, handle: u32) -> Option<&'static str> {
        let idx = self
            .handle_entries
            .binary_search_by(|entry| {
                entry
                    .group_path
                    .cmp(group_path)
                    .then_with(|| entry.handle.cmp(&handle))
            })
            .ok()?;
        Some(self.handle_entries[idx].field_name)
    }

    /// Number of entries.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the table is empty.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Categorisation of a decode failure -- distinguishes root cause so the
/// operator knows whether to fix the overlay type, the bit-count expectation,
/// or something structural.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DecodeErrorKind {
    /// BitReader reached EOF before the decoder finished consuming.
    Eof,
    /// Decoder finished but bits remained unconsumed.
    Residual,
    /// Zero-bit payload with a non-zero-expecting type.
    ZeroBits,
}

impl std::fmt::Display for DecodeErrorKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Eof => f.write_str("EOF"),
            Self::Residual => f.write_str("Residual"),
            Self::ZeroBits => f.write_str("ZeroBits"),
        }
    }
}

/// Accumulates per-(group, field, type, bit_count, error_kind) counts so the
/// operator can identify the dominant decode-error sources after an export run.
///
/// Designed for long-lived use: call [`Self::record`] on every failure, then
/// [`Self::top_n`] to get the sorted report.
#[derive(Debug, Clone, Default)]
pub struct OverlayErrorReport {
    /// Key: (group_path, field_name, field_type_tag, bit_count, error_kind).
    /// Value: occurrence count.
    counts: HashMap<(String, String, String, u32, DecodeErrorKind), u64>,
}

/// One row from the error report, sorted by descending count.
#[derive(Debug, Clone)]
pub struct OverlayErrorRow {
    pub count: u64,
    pub group_path: String,
    pub field_name: String,
    pub declared_type: String,
    pub bit_count: u32,
    pub error_kind: DecodeErrorKind,
}

impl OverlayErrorReport {
    /// Record a decode failure.
    pub fn record(
        &mut self,
        group_path: &str,
        field_name: &str,
        field_type: FieldType,
        bit_count: u32,
        kind: DecodeErrorKind,
    ) {
        let key = (
            group_path.to_owned(),
            field_name.to_owned(),
            format!("{field_type:?}"),
            bit_count,
            kind,
        );
        *self.counts.entry(key).or_insert(0) += 1;
    }

    /// Merge another report into this one (additive counts).
    pub fn merge_from(&mut self, other: &Self) {
        for (key, &count) in &other.counts {
            *self.counts.entry(key.clone()).or_insert(0) += count;
        }
    }

    /// Return the top `n` error sources sorted by descending count.
    pub fn top_n(&self, n: usize) -> Vec<OverlayErrorRow> {
        let mut rows: Vec<OverlayErrorRow> = self
            .counts
            .iter()
            .map(|((gp, fn_, dt, bc, ek), &cnt)| OverlayErrorRow {
                count: cnt,
                group_path: gp.clone(),
                field_name: fn_.clone(),
                declared_type: dt.clone(),
                bit_count: *bc,
                error_kind: *ek,
            })
            .collect();
        rows.sort_by_key(|r| std::cmp::Reverse(r.count));
        rows.truncate(n);
        rows
    }

    /// Total number of distinct error buckets.
    pub fn bucket_count(&self) -> usize {
        self.counts.len()
    }

    /// Total errors across all buckets.
    pub fn total_errors(&self) -> u64 {
        self.counts.values().sum()
    }
}

/// Statistics from an overlay pass.
#[derive(Debug, Clone, Default)]
pub struct OverlayStats {
    /// Fields where the type was known and decoding succeeded.
    pub decoded_ok: u64,
    /// Fields where the type was known but decoding failed.
    pub decoded_err: u64,
    /// Fields where the type is Raw/Skip (intentionally not decoded).
    pub raw_or_skip: u64,
    /// Fields where (group_path, field_name) had no entry in the table.
    pub not_in_table: u64,
    /// Fields where field_name was None (unmapped handle).
    pub no_field_name: u64,
    /// Detailed per-field error breakdown (populated only when reporting is on).
    pub error_report: OverlayErrorReport,
}

/// Result of applying the overlay to a single field.
pub struct OverlayResult {
    pub value_i64: Option<i64>,
    pub value_f64: Option<f64>,
    pub value_bool: Option<bool>,
    pub value_str: Option<String>,
}

/// Apply the type overlay to a single field.
///
/// Returns `None` if the field has no type mapping or is Raw/Skip.
/// Returns `Some(OverlayResult)` on success (values filled) or on decode
/// failure (all None -- the raw_bits remain).
pub fn apply_overlay(
    table: &OverlayTable,
    group_path: &str,
    field_name: Option<&str>,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    apply_overlay_inner(
        table, group_path, field_name, None, raw_bits, bit_count, stats,
    )
}

/// Apply the overlay with the replay field's handle available as a fallback.
///
/// Direct name lookup, including the narrow Unreal `b`-prefix fallback, stays
/// authoritative. The explicit handle is consulted only when both miss.
pub fn apply_overlay_with_handle(
    table: &OverlayTable,
    group_path: &str,
    field_name: Option<&str>,
    handle: u32,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    apply_overlay_inner(
        table,
        group_path,
        field_name,
        Some(handle),
        raw_bits,
        bit_count,
        stats,
    )
}

fn apply_overlay_inner(
    table: &OverlayTable,
    group_path: &str,
    field_name: Option<&str>,
    handle: Option<u32>,
    raw_bits: Option<&[u8]>,
    bit_count: u32,
    stats: &mut OverlayStats,
) -> Option<OverlayResult> {
    // Fall back to the `b`-prefixed spelling of the same field.
    //
    // The C# descriptors bind a property to its handle number and carry a name
    // only as a label, so a descriptor that spells a boolean
    // `bDeathMontageEffectOverrideIsQueued` still matches a wire field the
    // replay declares as `DeathMontageEffectOverrideIsQueued`. Our table is
    // keyed on the name, so that spelling difference makes the lookup miss and
    // the field stays raw -- 581 rows on 02d4d478, shipped as an undecoded
    // blob where the reference has a plain bool.
    //
    // Narrow by construction: this only fires when the direct lookup already
    // missed, and it can only hit an entry that the C# author spelled with the
    // Unreal boolean prefix. Measured across all 1,054 entries and every
    // undecoded row on 02d4d478, exactly one field resolves this way and it is
    // the correct one.
    let resolved = field_name
        .and_then(|name| {
            table
                .lookup(group_path, name)
                .or_else(|| table.lookup(group_path, &format!("b{name}")))
                .map(|field_type| (field_type, name))
        })
        .or_else(|| {
            handle
                .and_then(|value| table.lookup_handle(group_path, value))
                .and_then(|descriptor_name| {
                    table
                        .lookup(group_path, descriptor_name)
                        .map(|field_type| (field_type, field_name.unwrap_or(descriptor_name)))
                })
        });
    let (field_type, diagnostic_name) = match resolved {
        Some(resolved) => resolved,
        None => {
            if field_name.is_none() {
                stats.no_field_name += 1;
            } else {
                stats.not_in_table += 1;
            }
            return None;
        }
    };

    if matches!(field_type, FieldType::Raw | FieldType::Skip) {
        stats.raw_or_skip += 1;
        return None;
    }

    let data = match raw_bits {
        Some(d) if bit_count > 0 => d,
        _ => {
            // Zero-bit field with a typed decoder -- unusual but not an error.
            if bit_count == 0 && field_type == FieldType::EnumRemainingBits {
                stats.decoded_ok += 1;
                return Some(OverlayResult {
                    value_i64: Some(0),
                    value_f64: None,
                    value_bool: None,
                    value_str: None,
                });
            }
            stats.decoded_err += 1;
            stats.error_report.record(
                group_path,
                diagnostic_name,
                field_type,
                bit_count,
                DecodeErrorKind::ZeroBits,
            );
            return Some(OverlayResult {
                value_i64: None,
                value_f64: None,
                value_bool: None,
                value_str: None,
            });
        }
    };

    match decode_field(field_type, data, bit_count) {
        Ok(DecodedValue::I64(v)) => {
            stats.decoded_ok += 1;
            Some(OverlayResult {
                value_i64: Some(v),
                value_f64: None,
                value_bool: None,
                value_str: None,
            })
        }
        Ok(DecodedValue::F64(v)) => {
            stats.decoded_ok += 1;
            Some(OverlayResult {
                value_i64: None,
                value_f64: Some(v),
                value_bool: None,
                value_str: None,
            })
        }
        Ok(DecodedValue::Bool(v)) => {
            stats.decoded_ok += 1;
            Some(OverlayResult {
                value_i64: None,
                value_f64: None,
                value_bool: Some(v),
                value_str: None,
            })
        }
        Ok(DecodedValue::Str(v)) => {
            stats.decoded_ok += 1;
            Some(OverlayResult {
                value_i64: None,
                value_f64: None,
                value_bool: None,
                value_str: Some(v),
            })
        }
        Err(e) => {
            stats.decoded_err += 1;
            let kind = match &e {
                DecodeError::BitIo(_) => DecodeErrorKind::Eof,
                DecodeError::NotFullyConsumed { .. } => DecodeErrorKind::Residual,
                DecodeError::RawOrSkip => DecodeErrorKind::ZeroBits, // unreachable here
            };
            stats
                .error_report
                .record(group_path, diagnostic_name, field_type, bit_count, kind);
            Some(OverlayResult {
                value_i64: None,
                value_f64: None,
                value_bool: None,
                value_str: None,
            })
        }
    }
}
