"""Extract the three VALORANT payload-transform S-box tables from the upstream C#
source and emit them as a Rust module.

The tables are 256-byte permutation tables spliced across several C# string
literals inside `Convert.FromHexString(...)`. Copying them by hand (or via a
console round-trip) risks silent corruption, and a single wrong byte would make
the 13.00/13.02 transforms produce garbage that still *looks* plausible. So this
reads the literals directly, concatenates them, and refuses to emit anything
unless each table is exactly 512 hex chars / 256 unique byte values.

Usage:
    python tools/extract_sboxes.py <helpers.cs> <out.rs>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

if __package__:
    from .atomic_io import atomic_write_text
else:  # direct script execution
    from atomic_io import atomic_write_text

TABLES = ("SubstituteTable32", "SubstituteTable64", "SubstituteTable8")


def extract(source: str, name: str) -> bytes:
    """Pull one `static readonly byte[] <name> = Convert.FromHexString("..." + "...")` table."""
    # Grab everything from the declaration up to the closing paren+semicolon.
    m = re.search(
        rf"{re.escape(name)}\s*=\s*Convert\.FromHexString\((?P<body>.*?)\)\s*;",
        source,
        re.DOTALL,
    )
    if not m:
        raise SystemExit(f"table {name}: declaration not found")
    # Concatenate every double-quoted literal in the initialiser.
    hexstr = "".join(re.findall(r'"([0-9a-fA-F]*)"', m.group("body")))
    if len(hexstr) != 512:
        raise SystemExit(
            f"table {name}: expected 512 hex chars (256 bytes), got {len(hexstr)}"
        )
    data = bytes.fromhex(hexstr)
    if len(set(data)) != 256:
        raise SystemExit(
            f"table {name}: not a permutation of 0..255 "
            f"({len(set(data))} distinct values) -- extraction is wrong"
        )
    return data


def render(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, 256, 16):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 16]))
    body = "\n".join(rows)
    return f"pub static {name}: [u8; 256] = [\n{body}\n];\n"


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        raise SystemExit(__doc__)
    source = Path(argv[1]).read_text(encoding="utf-8")
    out = [
        "//! VALORANT payload-transform substitution tables.",
        "//!",
        "//! GENERATED by tools/extract_sboxes.py -- do not edit by hand.",
        "//!",
        "//! Each table is a permutation of 0..=255. They are shared across game",
        "//! builds: release-13.00 and release-13.02 use the identical tables, which",
        "//! is why upstream lifted them into a common helper when 13.02 landed.",
        "//! Because they are stable, they double as a byte signature for locating",
        "//! the transform routine when a new build has to be analysed.",
        "",
    ]
    for name in TABLES:
        data = extract(source, name)
        rust_name = "SBOX_" + name.replace("SubstituteTable", "")
        out.append(render(rust_name, data))
        print(f"{name}: 256 bytes, permutation verified -> SBOX_{name.replace('SubstituteTable', '')}")
    atomic_write_text(Path(argv[2]), "\n".join(out))
    print(f"wrote {argv[2]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
