#!/usr/bin/env python3
"""Generate `crates/vrf-decode/src/checksum_table.rs` from export manifests.

Every `NetFieldExport` the replay declares carries a `compatible_checksum`, and
Unreal hashes the property's *type* into it alongside its name. That makes the
checksum a content address: two fields sharing one are the same property, even
on classes the C# descriptors never described.

So a parameter no descriptor declares can take its type from a declared field
with the same checksum. This script learns that map -- for every
`(group_path, field_name)` the overlay table already types, it records
`checksum -> FieldType` -- and emits it as a sorted static slice.

**A checksum is not replay-specific.** It is derived from the property, so the
map holds for any replay carrying the same property. Verified across all five
supported builds: `Scale3D` is 2983776962 on 12.10, 12.11, 13.00, 13.01 and
13.02 alike. That is what makes a generated table correct here, where a table
of *groups* would have been a snapshot of whichever match was exported.

**Conflicts are dropped, and that is the safety property.** A checksum whose
donors disagree on the type is not written, so the mechanism refuses exactly the
cases that would mistype. On the reference corpus that drops two:
`AllianceFilter` (`EnumByte` vs `EnumRemainingBits`, equivalent at these widths
-- an inconsistency in the table, not on the wire) and `ReplicatedMovement`
(`ByteComponents` vs `ShortComponents`, genuinely different and different in
width). The second is the case a name-based rule would have got wrong.

Usage:
    python tools/extract_checksum_types.py --export out/probe [--export out/other]
    python tools/extract_checksum_types.py --export out/probe --check
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TABLE_RS = REPO / "crates" / "vrf-decode" / "src" / "table.rs"
OUT_RS = REPO / "crates" / "vrf-decode" / "src" / "checksum_table.rs"

#: One `OverlayEntry` literal. The type arm has to allow a braced payload
#: (`SerializedInt { max: 65536 }`) as well as a bare variant.
ENTRY_RE = re.compile(
    r'OverlayEntry \{\s*group_path: "((?:[^"\\]|\\.)*)",\s*'
    r'field_name: "((?:[^"\\]|\\.)*)",\s*'
    r'field_type: (FieldType::\w+(?:\s*\{[^}]*\})?)',
    re.S,
)

#: Types that carry no decode, so propagating them buys a consumer nothing.
UNTYPED = ("Raw", "Skip")

HEADER = """\
//! Generated by `tools/extract_checksum_types.py` -- do not edit by hand.
//!
//! `compatible_checksum` -> [`FieldType`], learned from the fields the overlay
//! table already types. Unreal hashes a property's type into its checksum, so
//! this identifies a property the way a name cannot: a parameter no descriptor
//! declares can take the type of a declared field sharing its checksum.
//!
//! Content-addressed and therefore build-stable -- the same property carries
//! the same checksum on 12.10 through 13.02. Checksums whose donors disagree on
//! the type are omitted, which is what keeps the mechanism from asserting the
//! cases it cannot settle.

use crate::decode::FieldType;

/// Sorted by checksum; binary-searched by `lookup_checksum`.
pub static CHECKSUM_TYPES: [(u32, FieldType); {count}] = [
"""


def unescape(raw: str) -> str:
    """Undo the escaping `extract_descriptors.py` writes into the Rust literal."""
    return raw.replace("\\\n", "").replace('\\"', '"').replace("\\\\", "\\")


def load_overlay_table() -> dict[tuple[str, str], str]:
    src = TABLE_RS.read_text(encoding="utf-8")
    return {
        (unescape(group), unescape(field)): " ".join(field_type.split())
        for group, field, field_type in ENTRY_RE.findall(src)
    }


def learn(manifests: list[Path], table: dict[tuple[str, str], str]):
    """`(map, conflicts)` -- checksum to type, and the ones that disagreed."""
    seen: dict[int, set[str]] = collections.defaultdict(set)
    names: dict[int, set[str]] = collections.defaultdict(set)
    for path in manifests:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for group in manifest.get("net_field_export_groups") or []:
            group_path = group.get("path") or ""
            for field in group.get("fields") or []:
                checksum, name = field.get("compatible_checksum"), field.get("name")
                if checksum is None or not name:
                    continue
                names[checksum].add(name)
                declared = table.get((group_path, name))
                if declared and not any(u in declared for u in UNTYPED):
                    seen[checksum].add(declared)
    resolved = {c: next(iter(t)) for c, t in seen.items() if len(t) == 1}
    conflicts = {c: (sorted(t), sorted(names[c])) for c, t in seen.items() if len(t) > 1}
    return resolved, conflicts


COMMITTED_RE = re.compile(r"\((\d+), (FieldType::[^)]*)\),")


def load_committed() -> dict[int, str]:
    """The checksum -> type map as currently committed."""
    if not OUT_RS.is_file():
        return {}
    src = OUT_RS.read_text(encoding="utf-8")
    return {int(c): " ".join(t.split()) for c, t in COMMITTED_RE.findall(src)}


class Verdict:
    """How a freshly learned map relates to the committed one.

    Three relations, and only one of them is a problem. `new` and `unseen` are
    both coverage: a checksum identifies a property, so a wider set of replays
    teaches a larger subset of the same truth and a narrower one teaches less.
    `disagreed` is the real thing -- one checksum mapped two ways, which means
    one of them is wrong.
    """

    def __init__(self, disagreed, new, unseen):
        self.disagreed, self.new, self.unseen = disagreed, new, unseen

    @property
    def ok(self) -> bool:
        return not self.disagreed


def reconcile(committed: dict[int, str], learned: dict[int, str]) -> Verdict:
    disagreed = {c: (committed[c], learned[c])
                 for c in committed.keys() & learned.keys()
                 if committed[c] != learned[c]}
    return Verdict(
        disagreed,
        {c: learned[c] for c in learned.keys() - committed.keys()},
        {c: committed[c] for c in committed.keys() - learned.keys()},
    )


def merge(committed: dict[int, str], learned: dict[int, str]) -> dict[int, str]:
    """Union, refusing a disagreement rather than picking a winner.

    Widening the basis must not narrow the table: an entry a smaller run cannot
    re-derive is still correct, and a plain regeneration would silently drop it.
    """
    clash = [c for c in committed.keys() & learned.keys()
             if committed[c] != learned[c]]
    if clash:
        raise ValueError(
            f"{len(clash)} checksum(s) disagree, refusing to merge: "
            + ", ".join(f"{c} {committed[c]} vs {learned[c]}"
                        for c in sorted(clash)[:5])
        )
    return {**committed, **learned}


def render(resolved: dict[int, str]) -> str:
    body = "".join(
        f"    ({checksum}, {resolved[checksum]}),\n" for checksum in sorted(resolved)
    )
    return HEADER.replace("{count}", str(len(resolved))) + body + "];\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, action="append", required=True,
                    help="directory written by `vrfkit export` (repeatable)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    args = ap.parse_args()

    manifests = [d / "manifest.json" for d in args.export]
    missing = [m for m in manifests if not m.is_file()]
    if missing:
        print(f"SKIP: no manifest at {missing[0]}", file=sys.stderr)
        return 0

    table = load_overlay_table()
    if not table:
        print(f"FAILED: parsed no entries out of {TABLE_RS}", file=sys.stderr)
        return 1
    resolved, conflicts = learn(manifests, table)
    rendered = render(resolved)

    for checksum, (types, names) in sorted(conflicts.items()):
        print(f"  dropped {checksum}: {names} declared as {types}")
    print(f"{len(table)} table entries, {len(manifests)} manifest(s) -> "
          f"{len(resolved)} checksums, {len(conflicts)} dropped")

    committed = load_committed()
    verdict = reconcile(committed, resolved)
    print(f"vs committed: {len(verdict.disagreed)} disagree, {len(verdict.new)} "
          f"new here, {len(verdict.unseen)} not taught by these manifests")
    for checksum, (was, now) in sorted(verdict.disagreed.items())[:10]:
        print(f"  DISAGREE {checksum}: committed {was}, learned {now}")

    if args.check:
        if not verdict.ok:
            print(f"FAILED: {len(verdict.disagreed)} checksum(s) map two ways",
                  file=sys.stderr)
            return 1
        print(f"\nOK: {OUT_RS.name} agrees with these manifests wherever they "
              f"overlap")
        return 0

    # Merge rather than replace. A checksum this basis did not happen to see is
    # still correct, so rendering fresh would drop it -- which is how the file
    # came to hold 417 entries that no reachable export set reproduces. Byte
    # equality with a regeneration was never achievable for a content-addressed
    # table, and demanding it is what made `--check` fail for every basis and
    # stop meaning anything.
    widened = merge(committed, resolved)
    OUT_RS.write_text(render(widened), encoding="utf-8")
    print(f"wrote {OUT_RS} ({len(widened)} checksums, +{len(verdict.new)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
