"""Extract the payload-transform golden vectors from the upstream C# test suite
and emit them as a Rust test-data module.

These 55 vectors are the only independent check that our port of the five
per-build transforms is bit-exact. Transcribing 36-byte hex strings by hand would
undermine that, so they are lifted mechanically and the count is asserted.

Usage:
    python tools/extract_golden.py <ValorantSeededTransformTests.cs> <out.rs>
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    from .atomic_io import atomic_write_text
except ImportError:  # direct script execution
    from atomic_io import atomic_write_text

EXPECTED_BRANCHES = (
    "++Ares-Core+release-12.10",
    "++Ares-Core+release-12.11",
    "++Ares-Core+release-13.00",
    "++Ares-Core+release-13.01",
    "++Ares-Core+release-13.02",
)
EXPECTED_BOUNDARIES = (0, 1, 7, 8, 31, 32, 63, 64, 65, 287, 288)
EXPECTED_CASE_COUNT = len(EXPECTED_BRANCHES) * len(EXPECTED_BOUNDARIES)

# Vectors are written either with an inline hex literal or with a reference to a
# `private const string` declared at the top of the fixture.
CONST_RE = re.compile(r'private\s+const\s+string\s+(\w+)\s*=\s*"([0-9A-Fa-f]*)"\s*;')
INT_CONST_RE = re.compile(r"private\s+const\s+(?:int|uint)\s+(\w+)\s*=\s*(\d+)\s*;")
CASE_RE = re.compile(
    r'new\(\s*"(?P<branch>[^"]+)"\s*,\s*(?P<bits>\d+)\s*,\s*(?P<hex>"[0-9A-Fa-f]*"|\w+)\s*\)'
)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        raise SystemExit(__doc__)
    src = Path(argv[1]).read_text(encoding="utf-8-sig")

    strings = {m.group(1): m.group(2) for m in CONST_RE.finditer(src)}
    ints = {m.group(1): int(m.group(2)) for m in INT_CONST_RE.finditer(src)}
    for required in ("PayloadHex",):
        if required not in strings:
            raise SystemExit(f"missing `{required}` constant in fixture")
    if "ActorNetGuid" not in ints:
        raise SystemExit("missing `ActorNetGuid` constant in fixture")

    cases = []
    for m in CASE_RE.finditer(src):
        raw = m.group("hex")
        if raw.startswith('"'):
            hexstr = raw.strip('"')
        elif raw in strings:
            hexstr = strings[raw]
        else:
            raise SystemExit(f"vector references unknown constant `{raw}`")
        bits = int(m.group("bits"))
        expected_bytes = (bits + 7) // 8
        if len(hexstr) // 2 != expected_bytes:
            raise SystemExit(
                f"{m.group('branch')} @ {bits} bits: expected {expected_bytes} bytes, "
                f"hex carries {len(hexstr) // 2}"
            )
        cases.append((m.group("branch"), bits, hexstr.upper()))

    if len(cases) != EXPECTED_CASE_COUNT:
        raise SystemExit(
            f"expected exactly {EXPECTED_CASE_COUNT} golden vectors, found {len(cases)}"
        )

    pairs = {(branch, bits) for branch, bits, _ in cases}
    expected_pairs = {
        (branch, bits)
        for branch in EXPECTED_BRANCHES
        for bits in EXPECTED_BOUNDARIES
    }
    if pairs != expected_pairs or len(pairs) != len(cases):
        missing = sorted(expected_pairs - pairs)
        unexpected = sorted(pairs - expected_pairs)
        duplicate_count = len(cases) - len(pairs)
        details = []
        if missing:
            details.append("missing " + ", ".join(f"{b} @ {n}" for b, n in missing))
        if unexpected:
            details.append(
                "unexpected " + ", ".join(f"{b} @ {n}" for b, n in unexpected)
            )
        if duplicate_count:
            details.append(f"{duplicate_count} duplicate vector(s)")
        raise SystemExit("invalid golden oracle: " + "; ".join(details))

    branches = sorted({c[0] for c in cases})
    # Regular `//` comments, not `//!`: this file is pulled in with `include!`,
    # and an inner doc comment is only legal at the top of a module.
    lines = [
        "// Golden payload-transform vectors.",
        "//",
        "// GENERATED by tools/extract_golden.py from the upstream C# fixture --",
        "// do not edit by hand.",
        "//",
        f"// {len(cases)} vectors across {len(branches)} builds. Bit counts are chosen to",
        "// exercise every staging boundary of the transform: 0, 1, 7 (tail only),",
        "// 8 (one byte), 31/32 (32-bit word edge), 63/64/65 (64-bit word edge) and",
        "// 287/288 (multi-word with and without a partial tail).",
        "",
        "/// The shared plaintext payload every vector transforms.",
        f'pub const PAYLOAD_HEX: &str = "{strings["PayloadHex"].upper()}";',
        "",
        "/// Actor net GUID used to derive the seed in the reference fixture.",
        f"pub const ACTOR_NET_GUID: u32 = {ints['ActorNetGuid']};",
        "",
        "/// `(branch, bit_count, expected_output_hex)`",
        f"pub const VECTORS: [(&str, usize, &str); {len(cases)}] = [",
    ]
    for branch, bits, hexstr in cases:
        lines.append(f'    ("{branch}", {bits}, "{hexstr}"),')
    lines.append("];")
    lines.append("")

    atomic_write_text(Path(argv[2]), "\n".join(lines))
    per_branch = {b: sum(1 for c in cases if c[0] == b) for b in branches}
    for b in branches:
        print(f"  {b}: {per_branch[b]} vectors")
    print(f"wrote {argv[2]} ({len(cases)} vectors total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
