#!/usr/bin/env python3
"""Generate `crates/vrf-decode/src/checksum_table.rs` from export manifests.

Every `NetFieldExport` the replay declares carries a `compatible_checksum`, and
Unreal hashes the property's *type* into it alongside its name. That makes the
checksum a content address: two fields sharing one are the same property, even
on classes the C# descriptors never described.

So a parameter no descriptor declares can take its type from a declared field
with the same checksum. This script learns that map -- for every
`(group_path, field_name)` the overlay table already types, it records
`checksum -> FieldType` -- and emits it as a sorted static slice.

**A checksum is not replay-specific.** It is derived from the property, so the
map holds for any replay carrying the same property. Verified across all five
supported builds: `Scale3D` is 2983776962 on 12.10, 12.11, 13.00, 13.01 and
13.02 alike. That is what makes a generated table correct here, where a table
of *groups* would have been a snapshot of whichever match was exported.

**Conflicts are dropped, and that is the safety property.** A checksum whose
donors disagree on the type is not written, so the mechanism refuses exactly the
cases that would mistype. On the reference corpus that drops two:
`AllianceFilter` (`EnumByte` vs `EnumRemainingBits`, equivalent at these widths
-- an inconsistency in the table, not on the wire) and `ReplicatedMovement`
(`ByteComponents` vs `ShortComponents`, genuinely different and different in
width). The second is the case a name-based rule would have got wrong.

Dropping decides what gets WRITTEN. It used to also end the story: the dropped
set never reached `reconcile`, so a checksum the file already commits and the
manifests now rule out passed `--check` and survived `merge`'s union. Conflicts
are now compared against the committed file -- ruled out is a failure, merely
ambiguous is reported.

Usage:
    python tools/extract_checksum_types.py --export out/probe [--export out/other]
    python tools/extract_checksum_types.py --export out/probe --check
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TABLE_RS = REPO / "crates" / "vrf-decode" / "src" / "table.rs"
OUT_RS = REPO / "crates" / "vrf-decode" / "src" / "checksum_table.rs"

#: One `OverlayEntry` literal. The type arm has to allow a braced payload
#: (`SerializedInt { max: 65536 }`) as well as a bare variant.
ENTRY_RE = re.compile(
    r'OverlayEntry \{\s*group_path: "((?:[^"\\]|\\.)*)",\s*'
    r'field_name: "((?:[^"\\]|\\.)*)",\s*'
    r'field_type: (FieldType::\w+(?:\s*\{[^}]*\})?)',
    re.S,
)

#: Types that carry no decode, so propagating them buys a consumer nothing.
UNTYPED = ("Raw", "Skip")

HEADER = """\
//! Generated by `tools/extract_checksum_types.py` -- do not edit by hand.
//!
//! `compatible_checksum` -> [`FieldType`], learned from the fields the overlay
//! table already types. Unreal hashes a property's type into its checksum, so
//! this identifies a property the way a name cannot: a parameter no descriptor
//! declares can take the type of a declared field sharing its checksum.
//!
//! Content-addressed and therefore build-stable -- the same property carries
//! the same checksum on 12.10 through 13.02. Checksums whose donors disagree on
//! the type are omitted, which is what keeps the mechanism from asserting the
//! cases it cannot settle.

use crate::decode::FieldType;

/// Sorted by checksum; binary-searched by `lookup_checksum`.
pub static CHECKSUM_TYPES: [(u32, FieldType); {count}] = [
"""


def unescape(raw: str) -> str:
    """Undo the escaping `extract_descriptors.py` writes into the Rust literal."""
    return raw.replace("\\\n", "").replace('\\"', '"').replace("\\\\", "\\")


def load_overlay_table() -> dict[tuple[str, str], str]:
    src = TABLE_RS.read_text(encoding="utf-8")
    return {
        (unescape(group), unescape(field)): " ".join(field_type.split())
        for group, field, field_type in ENTRY_RE.findall(src)
    }


def learn(manifests: list[Path], table: dict[tuple[str, str], str]):
    """`(map, conflicts)` -- checksum to type, and the ones that disagreed."""
    seen: dict[int, set[str]] = collections.defaultdict(set)
    names: dict[int, set[str]] = collections.defaultdict(set)
    for path in manifests:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for group in manifest.get("net_field_export_groups") or []:
            group_path = group.get("path") or ""
            for field in group.get("fields") or []:
                checksum, name = field.get("compatible_checksum"), field.get("name")
                if checksum is None or not name:
                    continue
                names[checksum].add(name)
                declared = table.get((group_path, name))
                if declared and not any(u in declared for u in UNTYPED):
                    seen[checksum].add(declared)
    resolved = {c: next(iter(t)) for c, t in seen.items() if len(t) == 1}
    conflicts = {c: (sorted(t), sorted(names[c])) for c, t in seen.items() if len(t) > 1}
    return resolved, conflicts


COMMITTED_RE = re.compile(r"\((\d+), (FieldType::[^)]*)\),")


def load_committed() -> dict[int, str]:
    """The checksum -> type map as currently committed."""
    if not OUT_RS.is_file():
        return {}
    src = OUT_RS.read_text(encoding="utf-8")
    return {int(c): " ".join(t.split()) for c, t in COMMITTED_RE.findall(src)}


class Verdict:
    """How a freshly learned map relates to the committed one.

    Five relations, and two of them are problems. `new` and `unseen` are both
    coverage: a checksum identifies a property, so a wider set of replays
    teaches a larger subset of the same truth and a narrower one teaches less.
    `disagreed` is the real thing -- one checksum mapped two ways, which means
    one of them is wrong.

    The last two come from the checksums `learn()` DROPPED. Dropping them is
    the safety property for what gets written, but it used to end the story:
    `conflicts` never reached this class, so a checksum the manifests now find
    ambiguous was compared against nothing and `--check` passed.

      `contradicted` the committed type is not among the candidate types at
                     all, so the new evidence rules it out. A problem.
      `ambiguous`    the committed type IS one of the candidates. That is a
                     narrower-basis entry, learned when only one donor was
                     visible -- the same case `unseen` is tolerated for.
                     Reported, not failed: a guard that cannot pass is not a
                     guard, and this file already learned that once.
    """

    def __init__(self, disagreed, new, unseen, contradicted=None, ambiguous=None):
        self.disagreed, self.new, self.unseen = disagreed, new, unseen
        self.contradicted = contradicted or {}
        self.ambiguous = ambiguous or {}

    @property
    def ok(self) -> bool:
        return not self.disagreed and not self.contradicted


def _committed_vs_conflicts(committed: dict[int, str], conflicts: dict):
    """`(contradicted, ambiguous)` -- see `Verdict`."""
    contradicted, ambiguous = {}, {}
    for checksum, (types, names) in (conflicts or {}).items():
        if checksum not in committed:
            continue
        bucket = ambiguous if committed[checksum] in types else contradicted
        bucket[checksum] = (committed[checksum], types, names)
    return contradicted, ambiguous


def reconcile(committed: dict[int, str], learned: dict[int, str],
              conflicts: dict | None = None) -> Verdict:
    disagreed = {c: (committed[c], learned[c])
                 for c in committed.keys() & learned.keys()
                 if committed[c] != learned[c]}
    contradicted, ambiguous = _committed_vs_conflicts(committed, conflicts)
    return Verdict(
        disagreed,
        {c: learned[c] for c in learned.keys() - committed.keys()},
        {c: committed[c] for c in committed.keys() - learned.keys()},
        contradicted,
        ambiguous,
    )


def merge(committed: dict[int, str], learned: dict[int, str],
          conflicts: dict | None = None) -> dict[int, str]:
    """Union, refusing a disagreement rather than picking a winner.

    Widening the basis must not narrow the table: an entry a smaller run cannot
    re-derive is still correct, and a plain regeneration would silently drop it.

    `conflicts` is refused for the same reason `clash` is. The write path never
    consults the verdict -- it reconciles, prints, then merges -- so without
    this a checksum the manifests rule out would be carried forward into the
    freshly written file by the very `{**committed, ...}` that protects the
    entries this basis merely did not see.
    """
    clash = [c for c in committed.keys() & learned.keys()
             if committed[c] != learned[c]]
    if clash:
        raise ValueError(
            f"{len(clash)} checksum(s) disagree, refusing to merge: "
            + ", ".join(f"{c} {committed[c]} vs {learned[c]}"
                        for c in sorted(clash)[:5])
        )
    contradicted, _ambiguous = _committed_vs_conflicts(committed, conflicts)
    if contradicted:
        raise ValueError(
            f"{len(contradicted)} committed checksum(s) are ruled out by these "
            f"manifests, refusing to merge: "
            + ", ".join(f"{c} {was} not in {types}"
                        for c, (was, types, _n) in sorted(contradicted.items())[:5])
        )
    return {**committed, **learned}


def render(resolved: dict[int, str]) -> str:
    body = "".join(
        f"    ({checksum}, {resolved[checksum]}),\n" for checksum in sorted(resolved)
    )
    return HEADER.replace("{count}", str(len(resolved))) + body + "];\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, action="append", required=True,
                    help="directory written by `vrfkit export` (repeatable)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    args = ap.parse_args()

    manifests = [d / "manifest.json" for d in args.export]
    missing = [m for m in manifests if not m.is_file()]
    if missing:
        print(f"SKIP: no manifest at {missing[0]}", file=sys.stderr)
        return 0

    table = load_overlay_table()
    if not table:
        print(f"FAILED: parsed no entries out of {TABLE_RS}", file=sys.stderr)
        return 1
    resolved, conflicts = learn(manifests, table)
    rendered = render(resolved)

    for checksum, (types, names) in sorted(conflicts.items()):
        print(f"  dropped {checksum}: {names} declared as {types}")
    print(f"{len(table)} table entries, {len(manifests)} manifest(s) -> "
          f"{len(resolved)} checksums, {len(conflicts)} dropped")

    committed = load_committed()
    verdict = reconcile(committed, resolved, conflicts)
    print(f"vs committed: {len(verdict.disagreed)} disagree, {len(verdict.new)} "
          f"new here, {len(verdict.unseen)} not taught by these manifests, "
          f"{len(verdict.contradicted)} ruled out, {len(verdict.ambiguous)} now "
          f"ambiguous")
    for checksum, (was, now) in sorted(verdict.disagreed.items())[:10]:
        print(f"  DISAGREE {checksum}: committed {was}, learned {now}")
    for checksum, (was, types, names) in sorted(verdict.ambiguous.items())[:10]:
        print(f"  ambiguous {checksum} ({names}): committed {was}, donors now "
              f"disagree over {types} -- still one of them, so not a failure")

    if args.check:
        if not verdict.ok:
            for checksum, (was, types, names) in sorted(
                    verdict.contradicted.items())[:10]:
                print(f"  RULED OUT {checksum} ({names}): committed {was}, "
                      f"donors declare {types}", file=sys.stderr)
            print(f"FAILED: {len(verdict.disagreed)} checksum(s) map two ways, "
                  f"{len(verdict.contradicted)} committed checksum(s) are ruled "
                  f"out by these manifests", file=sys.stderr)
            return 1
        print(f"\nOK: {OUT_RS.name} agrees with these manifests wherever they "
              f"overlap")
        return 0

    # Merge rather than replace. A checksum this basis did not happen to see is
    # still correct, so rendering fresh would drop it -- which is how the file
    # came to hold 417 entries that no reachable export set reproduces. Byte
    # equality with a regeneration was never achievable for a content-addressed
    # table, and demanding it is what made `--check` fail for every basis and
    # stop meaning anything.
    widened = merge(committed, resolved, conflicts)
    OUT_RS.write_text(render(widened), encoding="utf-8")
    print(f"wrote {OUT_RS} ({len(widened)} checksums, +{len(verdict.new)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
