[package]
name = "vrf-movement"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Decoder for VALORANT remote-character-movement RPC payload"

[dependencies]
vrf-bitio = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
